package com.miaoshapro.dao;

import com.miaoshapro.dataobject.UserDO;

public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Sep 19 17:12:38 CST 2019
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Sep 19 17:12:38 CST 2019
     */
    int insertSelective(UserDO record);

    /**
     * 根据id查询用户信息
     * @param id
     * @return
     */
    UserDO selectByPrimaryKey(int id);
}