server:
  port: 9000
mybatis:
  mapper-locations: classpath:mapping/*.xml

spring:
  datasource:
    name: miaoshapro
    url: jdbc:mysql://localhost:3306/miaoshapro?serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver