package com.miaoshapro.dataobject;

public class UserPwdDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pwd.id
     *
     * @mbg.generated Thu Sep 19 17:12:38 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pwd.upwd
     *
     * @mbg.generated Thu Sep 19 17:12:38 CST 2019
     */
    private String upwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pwd.user_id
     *
     * @mbg.generated Thu Sep 19 17:12:38 CST 2019
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pwd
     *
     * @mbg.generated Thu Sep 19 17:12:38 CST 2019
     */
    public UserPwdDO(Integer id, String upwd, Integer userId) {
        this.id = id;
        this.upwd = upwd;
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pwd
     *
     * @mbg.generated Thu Sep 19 17:12:38 CST 2019
     */
    public UserPwdDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pwd.id
     *
     * @return the value of user_pwd.id
     *
     * @mbg.generated Thu Sep 19 17:12:38 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pwd.id
     *
     * @param id the value for user_pwd.id
     *
     * @mbg.generated Thu Sep 19 17:12:38 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pwd.upwd
     *
     * @return the value of user_pwd.upwd
     *
     * @mbg.generated Thu Sep 19 17:12:38 CST 2019
     */
    public String getUpwd() {
        return upwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pwd.upwd
     *
     * @param upwd the value for user_pwd.upwd
     *
     * @mbg.generated Thu Sep 19 17:12:38 CST 2019
     */
    public void setUpwd(String upwd) {
        this.upwd = upwd == null ? null : upwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pwd.user_id
     *
     * @return the value of user_pwd.user_id
     *
     * @mbg.generated Thu Sep 19 17:12:38 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pwd.user_id
     *
     * @param userId the value for user_pwd.user_id
     *
     * @mbg.generated Thu Sep 19 17:12:38 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}